name: dkc_cabinet_configurator
version: 1.0.0+1
description: DKC Cabinet Configurator
publish_to: 'none'

dependencies:
  dio: ^4.0.6
  drift: ^1.6.0
  elementary: ^1.3.1
  firebase_crashlytics: ^2.8.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed: 2.0.3+1
  go_router: ^4.1.0
  logger: ^1.1.0
  path: ^1.8.1
  path_provider: ^2.0.11
  provider: ^6.0.3
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.15
  sqlite3_flutter_libs: ^0.5.8
  surf_logger: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.16.0
  dartz: ^0.10.1
  drift_dev: ^1.6.0
  elementary_test: ^1.1.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.1
  surf_lint_rules: ^1.5.0

environment:
  sdk: ">=2.17.0-0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/db/dkc_db.sqlite
